name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
  check-lockfiles:
    name: Check Lockfiles
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: if [ -f package-lock.json ]; then echo "'package-lock.json' exists. Please use 'pnpm' instead of 'npm'."; exit 1; fi
      - run: if [ -f yarn.lock ]; then echo "'yarn.lock' exists. Please use 'pnpm' instead of 'yarn'."; exit 1; fi
